python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/SingleCharacters/SloLeks_Validated_ASR_RandomSplit --train_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_ASR_RandomSplit/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_ASR_RandomSplit/sloleks_test_gfp.dict
python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/SingleCharacters/SloLeks_Validated_ASR_LemmaSplit_v2 --train_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_ASR_LemmaSplit_v2/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_ASR_LemmaSplit_v2/sloleks_test_gfp.dict
python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/SingleCharacters/SloLeks_Validated_TTS_RandomSplit --train_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_TTS_RandomSplit/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_TTS_RandomSplit/sloleks_test_gfp.dict
python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/SingleCharacters/SloLeks_Validated_TTS_LemmaSplit_v2 --train_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_TTS_LemmaSplit_v2/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/SingleCharacters/SloLeks_Validated_TTS_LemmaSplit_v2/sloleks_test_gfp.dict

python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/MultipleCharacters/SloLeks_Validated_ASR_RandomSplit --train_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_ASR_RandomSplit/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_ASR_RandomSplit/sloleks_test_gfp.dict
python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/MultipleCharacters/SloLeks_Validated_ASR_LemmaSplit_v2 --train_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_ASR_LemmaSplit_v2/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_ASR_LemmaSplit_v2/sloleks_test_gfp.dict
python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/MultipleCharacters/SloLeks_Validated_TTS_RandomSplit --train_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_TTS_RandomSplit/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_TTS_RandomSplit/sloleks_test_gfp.dict
python Phonetisaurus_g2p_v2.py --model ./results/Phonetisaurus/MultipleCharacters/SloLeks_Validated_TTS_LemmaSplit_v2 --train_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_TTS_LemmaSplit_v2/sloleks_train_gfp.dict --test_dict /storage/rsdo/jtdh/MultipleCharacters/SloLeks_Validated_TTS_LemmaSplit_v2/sloleks_test_gfp.dict
